import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Traffico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-l from-[transparent] to-[#EE4D47]  w-max ">
        {/* <HeroBackground></HeroBackground> */}
        <Image
          src="/heroBackground.png"
          alt="heroBackground"
          width={'1285'}
          height={'802'}
        ></Image>
      </div>
    </div>
  );
}
